CREATE TABLE candidates(
    id VARCHAR(40) NOT NULL,
    photo VARCHAR(255) DEFAULT NULL,
    given_name VARCHAR(50) NOT NULL,
    family_name VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    job_title VARCHAR(50) DEFAULT NULL,
    created_at TIMESTAMP CURRENT_TIMESTAMP,
    updated_at TIMESTAMP CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);